### ISSUE TITLE
Unexpected meta charset

### ISSUE THREAD

**Issue by dragmz** [AngleSharp/AngleSharp#779]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Steps to Reproduce

````C#
using AngleSharp.Html;
using AngleSharp.Html.Parser;
using System.IO;

namespace CharsetTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var parser = new HtmlParser();
            var doc = parser.ParseDocument("<!DOCTYPE html><html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta charset=\"us-ascii\" /><title></title></head><body>&#261;</body></html>");
            var sw = new StringWriter();
            doc.ToHtml(sw, HtmlMarkupFormatter.Instance);
            var html = sw.ToString();
        }
    }
}
````

This returns the following html:
````html
<!DOCTYPE html><html lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="us-ascii"><title></title></head><body>ą</body></html>
````

**Expected behavior:** [What you expected to happen]

I expect the html to keep the ````&#261;```` entity and the ````us-ascii```` charset or have the charset updated to "utf-8".

**Actual behavior:** [What actually happened]

The charset is still ````us-ascii```` but there's no ````ą```` char in this charset.

**Environment details:** [OS, .NET Runtime, ...]

Windows 10, .NET 4.7.2

**Comment by FlorianRappl** [comment]
I tried this in Chrome - its the same behavior as AngleSharp. The encoding has only an impact on the *interpretation*  of the source stream, not the available characters.

Have you tried this in Chrome (or some other evergreen browser) beforehand?

**Comment by dragmz** [comment]
It's all the same in Chrome, IE, Edge, Firefox and AngleSharp. I'm closing this issue as it's lack of my HTML knowledge rather than a bug in AngleSharp.
